<?php


include __DIR__ . "/get_data_funcs.php";


/**
 * hook_menu
 */
function ktmodule_menu()
{
  return include __DIR__. "/hooks/ktmenu_define.php";
}


/**
 *
 * hook_theme
 */
function ktmodule_theme() {
  return include __DIR__. "/hooks/kttheme_define.php";
}

/**
 * hook_block_info()
 */
function ktmodule_block_info() {
  $blocks = array(
    'cycle2banner' => array(
      'info' => t('滚动横幅块'),
      'cache' => DRUPAL_CACHE_PER_ROLE,
    ),
    'side_category_menu' => array(
      'info' => t('侧面产品分类'),
      'cache' => DRUPAL_CACHE_PER_ROLE,
    ),
    'side_contact_method' => array(
      'info' => t('侧面联系方式'),
      'cache' => DRUPAL_CACHE_PER_ROLE,
      ),
    'side_changxiao' => array(
        'info' => t('侧面畅销产品'),
        'cache' => DRUPAL_CACHE_PER_ROLE,
      ),
    'frt_tuijian' => array(
        'info' => t('首页推荐产品块'),
        'cache' => DRUPAL_CACHE_PER_ROLE,
      ),
    'com_introduction' => array(
      'info' => t("公司介绍"),
      'cache' => DRUPAL_CACHE_PER_ROLE,
      ),
    'com_zuixingongying' => array(
      'info' => t("最新供应"),
      'cache' => DRUPAL_CACHE_PER_ROLE,
      ),
    'friend_link' => array(
      'info' => t("友情链接"),
      'cache' => DRUPAL_CACHE_PER_ROLE,
      ),
    'banner_gonggao' => array(
      'info' => t('网站公告'),
      'cache' => DRUPAL_CACHE_PER_ROLE,
      ),

  );
  return $blocks;
}

/**
 * hook_block_view()
 */
function ktmodule_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'cycle2banner'://横幅模块
      
      $block['subject'] = t('滚动横幅');
      //$block['content'] = $html;
      $block['content'] = theme('cycle2banner', array('images' => ktGetBannerData()));
      break;
    case 'side_category_menu': //侧面产品分类
      $data = kt_side_category_menu();
      $block = array(
        'subject' => t('产品分类'),
        'content' => theme('side_category', $data),
      );
      break;
    case 'side_contact_method': //侧面联系方式
      $block=array(
        'subject' => t('联系方式'),
        'content' => theme('side_contact', array()),
        );
      break;
    case 'side_changxiao': //侧面畅销产品
      $block = array(
          'subject' => t('畅销产品'),
          'content' => theme('side_changxiao', array()),
        );
      break;
    case 'frt_tuijian':
      $block = array(
        'subject' => t('推荐产品'),
        'content' => theme('frt_tuijian', array()),
        );
      break;
    case 'com_introduction':
      $node = node_load(9);
      $contentItem = field_get_items('node', $node, 'body'); 
      $con = $contentItem[0]['safe_value'];
      $imgItem = field_get_items('node', $node, 'field_image');
      $imgUrl = image_style_url("com_introduce", $imgItem[0]['uri']);
      $block = array(
        'subject' => t('公司介绍'),
        'content' => theme('com_introduction', array('content'=>$con, 'imgUrl'=>$imgUrl)),
        );
      break;
    case 'com_zuixingongying':
      $block = array(
        'subject' => t('最新供应'),
        'content' => theme('com_zuixingongying', array()),
        );
      break;
    case 'friend_link':
      $block = array(
        'subject' => t("友情链接"),
        'content' => theme('friend_link', array()),
        );
      break;
    case 'banner_gonggao':
      $block = array(
        'subject' => t("网站公告"),
        'content' => theme('banner_gonggao', array()),
        );
      break;
  }

  return $block;
}
