<?php

include __DIR__."/funcs/blocks.php";
/**
 * hook_block_info()
 */
function ktmodule_block_info()
{
    $blocks['cycle2banner'] = array(
        'info' => t('滚动横幅块'),
        'cache' => DRUPAL_CACHE_PER_ROLE,
    );
    return $blocks;
}



/**
 * hook_block_view()
 */
function ktmodule_block_view($delta = '')
{
  $block = array();
  $images = ktGetBannerData();
  $html = '<div class="slide myslide" data-cycle-fx="fade" data-cycle-timeout="5000"
        data-cycle-slides="> a"
       data-cycle-easing="linear"><div class="cycle-pager"></div>';
  foreach($images as $i){
    $html .= '<a href="'. $i['url'] .'" style="background-image:url('.$i['img'].');"></a>';
  }
  $html .= '</div>';

  switch($delta){
      case 'cycle2banner'://横幅模块
        //drupal_add_js('misc/jquery-1.11.1.min.js','file');
        drupal_add_js('sites/all/libraries/jquery.cycle/jquery.cycle2.min.js','file');
        $block['subject'] = t('滚动横幅');
        $block['content'] = $html;
  }

  return $block;
}

/**
 * hook_theme
 */
function ktmodule_theme()
{
  return array();
}